collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3936567
  brandStrength: 0.8712686
  rhythmicContrast: 0.9328358
  brandColors:
    - '#030404'
    - '#436392'
    - '#6587AC'
    - '#777777'
    - '#4B545C'
  lightness: 0.07182836
typography_spectrum: 0.2961754
layout_spectrum: 1
name: Sunset Road
